# These are supported funding model platforms

github: 'https://github.com/0xBSC-Project'
patreon: #none
open_collective: # Replace with a single Open Collective username
ko_fi: # not applicable
tidelift: #  npm/babel
community_bridge: # Linked Telegram
